extends:
  - google
  - plugin:react/recommended

parser: babel-eslint

env:
  browser: true
  node: true
  es6: true

plugins:
  - react

parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true

globals:
  console: false
  window: false
  chrome: false
  require: false
  localStorage: false
  sessionStorage: false
  setInterval: false
  setTimeout: false
  createjs: false
  clearInterval: false
  clearTimeout: false
  module: false
  XMLHttpRequest: false
  process: false

rules:
  max-len: [1, 80, 4, {ignoreComments: true, ignoreUrls: true, ignoreStrings: true, ignoreTemplateLiterals: true}]
  switch-colon-spacing: 0
